//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AccountInfo
{
    public string AccountNumber { get; set; }
    public decimal Balance { get; set; }
}

public partial class Customer
{
    public string AccountNumber { get; set; }
    public string Name { get; set; }
    public System.DateTime DOB { get; set; }
    public int MobileNumber { get; set; }
}

public partial class MOStatusTable
{
    public string EndUserName { get; set; }
    public byte[] EndUserPhoto { get; set; }
    public System.DateTime DOB { get; set; }
    public decimal AmountTransferred { get; set; }
    public int EndUserMobileNumber { get; set; }
    public int PIN { get; set; }
    public string Status { get; set; }
    public string AccountNumber { get; set; }
    public string VendorInformation { get; set; }
}

public partial class Transaction
{
    public string EndUserName { get; set; }
    public byte[] EndUserPhoto { get; set; }
    public System.DateTime DOB { get; set; }
    public decimal AmountTransferred { get; set; }
    public int EndUserMobileNumber { get; set; }
    public int PIN { get; set; }
    public string Status { get; set; }
    public string AccountNumber { get; set; }
    public string VendorInformation { get; set; }
}

public partial class UserCredential
{
    public string LoginID { get; set; }
    public string Password { get; set; }
    public string AccountNumber { get; set; }
}
